name: cups
services:
  cups:
    build:
      context: .
      dockerfile: Dockerfile
    image: cups-samsung:latest
    container_name: cups
    privileged: true
    volumes:
      - /dev:/dev:z
      - /run/dbus:/run/dbus:z
      - ./cupsd.conf:/etc/cups/cupsd.conf:Z
    ports:
      - 631:631/tcp
    restart: always
